// wv_rx.sv -- WAVEFORM VIGNETTE for uart_rx.
//
// NOT A TEST. A demonstration: one deliberately staged scenario, a
// reader-sized VCD, zero checks contributed to the suite. Not run by
// test/run.sh.
//
// ---------------------------------------------------------------------------
// WHAT A READER SHOULD LOOK AT
// ---------------------------------------------------------------------------
// That the receiver samples in the MIDDLE of each bit cell, not at its edges.
// This is the whole reason the receiver oversamples at all, and it is what
// buys the +/-3 % far-end tolerance REQ-011 sweeps: a sample taken at a bit
// boundary is one clock away from reading the neighbouring bit, while a sample
// taken mid-cell has 216 cycles of margin on either side.
//
// Three things are on the picture together:
//   * `rx_line` -- the driven frame, and the falling edge that starts it.
//   * `dut`'s own oversample tick -- one level of hierarchy is dumped, so the
//     ticks the receiver actually counts are visible rather than described.
//   * `spec_sample` -- a bench-side marker, ONE CYCLE WIDE, pulsed at the
//     cycles SPEC SS5.3 says the receiver must sample: 216 + 432*n for
//     n = 0..9, measured from the cycle in which the synchronised falling
//     edge is detected. This is the SPECIFICATION's prediction, generated by
//     this bench from the spec's arithmetic; it is not read from the design.
//     A reader lines it up against `rx_line` and sees each pulse land in the
//     middle of a cell, and against the DUT's ticks and sees which tick of
//     each group of sixteen is the sampling one (tick 8 of 16).
//
// `cyc_since_edge` carries the spec's own cycle numbering so the reader can
// read the 216 and the 432 straight off the bus rather than counting edges.
//
// The stop bit's sample at cycle 4104 is the last one; `rx_strobe` follows a
// couple of cycles later (registered output plus the two-flop input
// synchroniser), with `rx_byte` valid in that cycle.
//
// ---------------------------------------------------------------------------
// PARAMETER CHOICES, AND WHY
// ---------------------------------------------------------------------------
//   byte = 8'h3A     Asymmetric under bit reversal (0x3A = 0011_1010, LSB
//                    first on the wire: 0,1,0,1,1,1,0,0), and it has adjacent
//                    equal bits in both polarities -- so a reader can see that
//                    the mid-cell sample points are what resolve the run of
//                    ones, and that no cell boundary is ambiguous.
//   P = 432          The sender's bit period, set to the receiver's own
//                    nominal receive bit period (DIV_OS x OS = 27 x 16, SPEC
//                    SS2) so that the picture shows the IDEAL alignment: every
//                    sample dead-centre. A vignette is the wrong place to show
//                    tolerance; REQ-011's 6656-check sweep is where the
//                    422..447 window is actually established, and that sweep
//                    is unreadable as a waveform, which is why this file
//                    exists.
//   DIV_OS = 27      The real divisor. SPEC SS5.3 declares no parameter on
//                    uart_rx -- the constants live in uart_pkg (SPEC SS4) --
//                    so a bench derived from the specification has no legal
//                    way to shrink it. One frame is 4320 cycles; the VCD stays
//                    small because the signal list is short.
`timescale 1ns/1ps

module wv_rx;

  localparam int CLK_PERIOD_NS = 20;      // 50 MHz, SPEC SS2
  localparam int DIV_OS        = 27;      // SPEC SS2
  localparam int OS            = 16;      // SPEC SS2
  localparam int P             = DIV_OS * OS;  // 432, the sender bit period used here
  localparam int FIRST_SAMPLE  = 8 * DIV_OS;   // 216: oversample tick 8, SPEC SS5.3
  localparam logic [7:0] SHOW  = 8'h3A;   // see header

  logic clk = 1'b0;
  always #(CLK_PERIOD_NS/2) clk = ~clk;

  logic       rst;
  logic       rx_line;
  logic [7:0] rx_byte;
  logic       rx_strobe;
  logic       rx_frame_err;
  logic       rx_busy;

  uart_rx dut (
      .clk          (clk),
      .rst          (rst),
      .rx_line      (rx_line),
      .rx_byte      (rx_byte),
      .rx_strobe    (rx_strobe),
      .rx_frame_err (rx_frame_err),
      .rx_busy      (rx_busy)
  );

  // ---- Reader markers, generated from SPEC SS5.3's arithmetic.
  // `framing` is raised by the stimulus on the cycle the bench drives the
  // falling edge. The specification anchors cycle 0 at the cycle in which the
  // SYNCHRONISED edge is detected, which is two cycles later (SS5.3's explicit
  // two-flop synchroniser), so the marker counter is offset by SYNC_DELAY and
  // that offset is written out rather than folded into a constant.
  localparam int SYNC_DELAY = 2;

  logic                framing;
  logic signed [15:0]  cyc_since_edge;  // 0 = the cycle the synchronised edge is detected
  logic                spec_sample;     // one-cycle pulse at each spec-predicted sample
  logic [3:0]          cell_idx;        // 0 = start, 1..8 = d0..d7, 9 = stop, 15 = idle

  // A single counter, anchored so that the SYNCHRONISED edge cycle reads 0.
  // The bench raises `framing` on the negedge at which it drives the falling
  // edge, so the first posedge with framing high is raw cycle 0 and the spec's
  // cycle 0 is two posedges later; the counter therefore starts at -SYNC_DELAY
  // and the offset stays visible on the waveform (it reads -2, -1, 0) instead
  // of being folded away into a constant. One counter rather than two: a
  // second per-cycle bus in the dump costs ~80 KB and shows a reader nothing.
  always @(posedge clk) begin
    if (!framing) cyc_since_edge <= -SYNC_DELAY;
    else          cyc_since_edge <= cyc_since_edge + 16'sd1;
  end

  // Written as two single-assignment expressions rather than as a
  // default-then-override block: an intermediate assignment inside an
  // always @(*) re-evaluated every cycle shows up in the VCD as a pair of
  // value changes per cycle, which measured 30 KB of this file for nothing.
  always @(*) begin
    // SPEC SS5.3: sample at clock cycles 216 + 432*n for n = 0..9.
    spec_sample = framing && (cyc_since_edge >= FIRST_SAMPLE)
                          && (((cyc_since_edge - FIRST_SAMPLE) % P) == 0)
                          && (((cyc_since_edge - FIRST_SAMPLE) / P) <= 9);

    cell_idx    = (!framing || cyc_since_edge < 0 || (cyc_since_edge / P) > 9)
                  ? 4'd15
                  : 4'(cyc_since_edge / P);
  end

  initial begin
    $dumpfile("build/wave/wv_rx.vcd");
    // Depth 2 on the named bench scope: the receiver's ports and the three
    // markers, plus ONE level of children -- which is what puts the oversample
    // ticks the receiver actually counts on the picture beside the
    // spec-predicted sample marker. Depth 0 would drag in every internal
    // register of every instance and make the file unreadable, which is the
    // failure mode this vignette exists to avoid.
    $dumpvars(2, wv_rx);
  end

  // ---- Bench-model transmitter, written from SPEC SS3 (start low, d0..d7 LSB
  // first, stop high). Deliberately NOT uart_tx: the receiver's picture must
  // not depend on the transmitter being correct.
  task automatic drive_bit(input logic val, input int p);
    @(negedge clk);
    rx_line = val;
    repeat (p) @(posedge clk);
  endtask

  int i;

  initial begin
    $display("==== VIGNETTE (wv_rx) ====");
    $display("Look at spec_sample against rx_line: each one-cycle pulse lands in the MIDDLE of a bit cell (cycle 216 + 432*n from the synchronised falling edge), never at a boundary -- that mid-cell margin is what buys the far-end tolerance. dut.* shows the oversample ticks the receiver actually counts; the sampling one is tick 8 of every 16.");

    rst     = 1'b1;
    rx_line = 1'b1;   // line idles high, SPEC SS3
    framing = 1'b0;
    repeat (5) @(negedge clk);
    rst = 1'b0;
    repeat (20) @(posedge clk);

    // ---- One frame. framing is raised on the negedge at which the bench
    // drives the falling edge, so raw_count counts from the first posedge at
    // which the line is low.
    @(negedge clk);
    rx_line = 1'b0;
    framing = 1'b1;
    repeat (P) @(posedge clk);                                  // start bit
    for (i = 0; i < 8; i = i + 1) drive_bit(SHOW[i], P);        // d0..d7, LSB first
    drive_bit(1'b1, P);                                         // stop bit

    // ---- Tail: rx_strobe lands a couple of cycles after the stop sample at
    // cycle 4104, so hold the dump open long enough to contain it and the
    // return to idle.
    repeat (40) @(posedge clk);
    $display("  rx_byte at end of frame = 0x%02x (driven 0x%02x); rx_strobe seen = %0b, rx_frame_err seen = %0b",
             rx_byte, SHOW, strobe_seen, frame_err_seen);
    framing = 1'b0;
    repeat (20) @(posedge clk);

    $display("  VCD: build/wave/wv_rx.vcd");
    $finish;
  end

  // ---- Informational only ($display, never a check): confirms in text what
  // the picture shows, so the two can be compared.
  logic strobe_seen    = 1'b0;
  logic frame_err_seen = 1'b0;
  always @(posedge clk) begin
    if (rx_strobe)    strobe_seen    <= 1'b1;
    if (rx_frame_err) frame_err_seen <= 1'b1;
  end

endmodule
